<?php
/**
 * @file
 * Code for the Foodie Core feature.
 */

/*----------------------------------------------------------------------------
      SETUP & CONFIG
----------------------------------------------------------------------------*/

include_once 'foodie_core.features.inc';
include_once 'includes/class.efq.inc';

if (module_exists('devtools')) {
  devtools_load();
}

/*----------------------------------------------------------------------------
      DRUPAL HOOKS
----------------------------------------------------------------------------*/

/**
 * Implements hook_menu().
 */
function foodie_core_menu() {
  $items['front'] = array(
    'page callback' => 'foodie_core_front_page',
    'access callback' => TRUE,
    'file' => 'foodie_core.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/*----------------------------------------------------------------------------
      MODULE HOOKS
----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------
      INTERNAL
----------------------------------------------------------------------------*/



